ARDUINO_DIR = /usr/share/arduino/


  
BOARD = atemga328
TARGET       = CLItest
MCU          = atmega328p
F_CPU        = 16000000
SERIALDEV = /dev/ttyS0

ARDUINO_LIBS = 

include /data/arduino-mk-0.5/Arduino.mk
