ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java

TARGET       = CLItest
MCU          = atmega168
F_CPU        = 16000000
SERIALDEV = /dev/cu.usb*

ARDUINO_LIBS = LiquidCrystal

include /data/arduino-mk-latest/Arduino.mk
