ARDUINO_DIR = /usr/share/arduino/

  
TARGET       = CLItest
MCU          = atmega32u4
F_CPU        = 16000000
SERIAL_PORT = /dev/ttyS0
AVR_TOOLS_PATH = /usr/bin/
AVRDUDE_TOOLS_PATH = /usr/bin/
AVRDUDE_ETC_PATH = /etc/avrdude/
AVRDUDE_ARD_BAUDRATE = 57600

ISP_PROG = -c arduino
ARDUINO_LIBS = x10

include /data/arduino-mk-latest/Arduino.mk
