ARDUINO_DIR = /usr/share/arduino/

  
TARGET       = CLItest
MCU          = atmega328p
F_CPU        = 16000000
ARDUINO_PORT = /dev/ttyS0
AVR_TOOLS_PATH = /usr/bin/

ARDUINO_LIBS = x10

include /data/arduino-mk-0.5/Arduino.mk
