ARDUINO_DIR = /usr/share/arduino/

  
  TARGET       = CLItest
  MCU          = atmega32u4
  F_CPU        = 16000000
  SERIAL_PORT = /dev/ttyACM1
  AVR_TOOLS_PATH = /usr/bin/
  AVRDUDE_TOOLS_PATH = /usr/bin/
  AVRDUDE_ETC_PATH = /etc/avrdude/
  USB_VID = 0x26ba
  USB_PID = 0x8003
  ISP_PROG = -c arduino
  ARDUINO_LIBS = x10
  BOARD_TAG = leonardo
  BOARD_SUB = atmega32u4

include /data/git/Arduino-Makefile/Arduino.mk

